#!/usr/bin/env python3
"""Turns the bare-cross SVG into an Android VectorDrawable.

Called by scripts/generate_icons.sh for the adaptive icon's monochrome
(themed-icon) layer: the launcher only reads the alpha, so a vector is the
faithful choice — no density tables, crisp at any size.

The brand mark is a single <path> of absolute M/C/Z commands, which is
exactly the grammar android:pathData accepts, so the path is copied verbatim
after normalising the numbers (fixed decimals, no exponents — Android's
PathParser copes with `1e-05`, but not every launcher's does).

Usage: svg_mark_to_vector.py IN.svg OUT.xml --canvas DP --mark DP [--fill #RRGGBB]
       --canvas  viewport size in dp (108 for an adaptive icon layer)
       --mark    size the mark's bounding box is scaled to, centred on the canvas
"""
import argparse
import re
import sys

_NUMBER = re.compile(r"-?\d*\.?\d+(?:[eE][-+]?\d+)?")


def _fixed(match: "re.Match[str]") -> str:
    text = ("%.3f" % float(match.group(0))).rstrip("0").rstrip(".")
    return text if text not in ("", "-0", "-") else "0"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("svg")
    parser.add_argument("out")
    parser.add_argument("--canvas", type=float, required=True)
    parser.add_argument("--mark", type=float, required=True)
    parser.add_argument("--fill", default="#C1121F")
    args = parser.parse_args(argv[1:])

    with open(args.svg, encoding="utf-8") as fh:
        svg = fh.read()

    view_box = re.search(r'viewBox="([^"]+)"', svg)
    if not view_box:
        print(f"{args.svg}: no viewBox", file=sys.stderr)
        return 1
    _, _, vb_w, vb_h = (float(v) for v in view_box.group(1).replace(",", " ").split())
    if abs(vb_w - vb_h) > 1e-6:
        print(f"{args.svg}: viewBox must be square, got {vb_w}x{vb_h}", file=sys.stderr)
        return 1

    paths = re.findall(r"<path\b[^>]*\sd=\"([^\"]+)\"", svg)
    if len(paths) != 1:
        print(f"{args.svg}: expected exactly one <path>, found {len(paths)}", file=sys.stderr)
        return 1
    unsupported = set(re.findall(r"[A-Za-z]", paths[0])) - set("MCZmczLlHhVvSsQqTtAae")
    if unsupported:
        print(f"{args.svg}: path commands not understood: {sorted(unsupported)}", file=sys.stderr)
        return 1
    path_data = _NUMBER.sub(_fixed, paths[0].strip())

    scale = args.mark / vb_w
    offset = (args.canvas - args.mark) / 2
    fmt = lambda v: ("%.4f" % v).rstrip("0").rstrip(".")  # noqa: E731
    canvas = fmt(args.canvas)

    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icons.sh from assets/brand/templar-cross.svg.
     Do not edit: change the SVG and rerun the script. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{canvas}dp"
    android:height="{canvas}dp"
    android:viewportWidth="{canvas}"
    android:viewportHeight="{canvas}">
    <!-- Mark scaled to {fmt(args.mark)}dp and centred: same placement as the
         raster foreground layer. Only the alpha matters to a themed icon. -->
    <group
        android:translateX="{fmt(offset)}"
        android:translateY="{fmt(offset)}"
        android:scaleX="{fmt(scale)}"
        android:scaleY="{fmt(scale)}">
        <path
            android:fillColor="{args.fill}"
            android:pathData="{path_data}"/>
    </group>
</vector>
"""
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(xml)
    print(f"wrote {args.out} ({fmt(args.mark)}dp mark on a {canvas}dp canvas)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
