//! Liquid multisig: CT descriptor builder and PSET coordinator.
//!
//! Builds `ct(slip77(KEY), elwsh(multi(M, xpubs...)))` descriptors for
//! Liquid multisig wallets with confidential transactions.

use lwk_common::{Bip, Signer};
use lwk_signer::SwSigner;
use lwk_wollet::elements::pset::PartiallySignedTransaction;
use lwk_wollet::elements_miniscript::confidential::Key as BlindingKey;
use lwk_wollet::elements_miniscript::descriptor::DescriptorSecretKey;
use lwk_wollet::elements_miniscript::{Descriptor, DescriptorPublicKey};
use lwk_wollet::hashes::{sha256, Hash};
use lwk_wollet::WolletDescriptor;

use crate::error::{LiquidError, TemplarError};

/// Jade stores a registered multisig under a name of at most 16 characters.
pub const JADE_MULTISIG_NAME_MAX: usize = 16;

/// Blinding key source for Liquid multisig wallets.
#[derive(Debug, Clone)]
pub enum BlindingKeySource {
    /// Random SLIP77 key generated by the coordinator.
    RandomSlip77,
    /// Deterministic SLIP77 key derived from a BIP39 mnemonic seed.
    DeterministicSlip77 {
        /// The seed bytes to derive the blinding key from.
        seed_hex: String,
    },
    /// Deterministic from the descriptor itself: every party that holds the
    /// same N public keys derives the same blinding key, so a co-signer can
    /// rebuild the wallet from the keys alone — the way a Bitcoin
    /// `sortedmulti` already works.
    ///
    /// The 32 bytes are the
    /// [ELIP151](https://github.com/ElementsProject/ELIPs/blob/main/elip-0151.mediawiki)
    /// digest of the script descriptor, but used as a **SLIP77 master key**
    /// (`slip77(<hex>)`) rather than as ELIP151's single view key: SLIP77 is
    /// the one form a Jade's multisig registration can carry, and a
    /// per-script key is what every other Templar wallet already blinds with.
    /// Not interoperable with a wallet that applies ELIP151 literally — such a
    /// wallet imports this descriptor, key included, as it would any other.
    Elip151,
}

/// Setup helper for creating Liquid multisig wallets.
///
/// Coordinates xpub exchange and descriptor construction for
/// `ct(slip77(...), elwsh(multi(M, ...)))` wallets.
pub struct LiquidMultisigSetup;

impl LiquidMultisigSetup {
    /// Derives the keyorigin+xpub string for a signer using BIP87.
    ///
    /// Returns a string like `[fingerprint/87h/1h/0h]tpub...`
    pub fn derive_xpub(signer: &SwSigner) -> Result<String, TemplarError> {
        signer
            .keyorigin_xpub(Bip::Bip87, false)
            .map_err(|e| LiquidError::InvalidDescriptor(format!("keyorigin_xpub: {e}")).into())
    }

    /// Builds a Liquid multisig CT descriptor.
    ///
    /// # Arguments
    /// * `threshold` — number of required signers (M in M-of-N)
    /// * `xpubs` — keyorigin+xpub strings from each participant
    ///   (from `derive_xpub` or imported)
    /// * `blinding` — blinding key source
    ///
    /// # Returns
    /// A validated CT descriptor string:
    /// `ct(slip77(...),elwsh(sortedmulti(M,...)))`. `sortedmulti`, as on the
    /// Bitcoin side: the keys are ordered by BIP67 inside the script, so the
    /// order they were collected in does not change the wallet — two
    /// co-signers who each typed the keys in differently still hold one
    /// wallet.
    pub fn build_descriptor(
        threshold: usize,
        xpubs: &[String],
        blinding: &BlindingKeySource,
    ) -> Result<String, TemplarError> {
        if xpubs.is_empty() {
            return Err(LiquidError::InvalidDescriptor("No xpubs provided".into()).into());
        }
        if threshold == 0 || threshold > xpubs.len() {
            return Err(LiquidError::InvalidDescriptor(format!(
                "Invalid threshold {}-of-{}",
                threshold,
                xpubs.len()
            ))
            .into());
        }

        let blinding_hex = match blinding {
            BlindingKeySource::RandomSlip77 => {
                let mut key = [0u8; 32];
                getrandom::getrandom(&mut key)
                    .map_err(|e| LiquidError::InvalidDescriptor(format!("RNG failed: {e}")))?;
                hex::encode(key)
            }
            BlindingKeySource::DeterministicSlip77 { seed_hex } => {
                crate::derivation::slip77_blinding_key(&hex::decode(seed_hex).map_err(|e| {
                    LiquidError::InvalidDescriptor(format!("Invalid seed hex: {e}"))
                })?)
            }
            BlindingKeySource::Elip151 => Self::elip151_master_key_hex(threshold, xpubs)?,
        };

        let descriptor = format!(
            "ct(slip77({blinding_hex}),{})",
            Self::script_descriptor(threshold, xpubs)
        );

        // Validate by parsing with LWK
        let _wd: WolletDescriptor = descriptor
            .parse()
            .map_err(|e| LiquidError::InvalidDescriptor(format!("LWK rejected descriptor: {e}")))?;

        Ok(descriptor)
    }

    /// The unblinded half: `elwsh(sortedmulti(M,key/<0;1>/*,...))`.
    ///
    /// The keys are also written in one canonical (lexical) order. `sortedmulti`
    /// already makes the *scripts* order-independent; sorting the text too
    /// makes the descriptor byte-identical on every co-signer's device, so
    /// the string a wallet exports, and the name it registers on a Jade
    /// (a digest of this string), agree everywhere.
    fn script_descriptor(threshold: usize, xpubs: &[String]) -> String {
        let mut keys: Vec<String> = xpubs.iter().map(|x| format!("{x}/<0;1>/*")).collect();
        keys.sort();
        format!("elwsh(sortedmulti({threshold},{}))", keys.join(","))
    }

    /// The ELIP151 digest of this script descriptor, as the 32 hex bytes a
    /// `slip77(...)` clause takes — see [`BlindingKeySource::Elip151`].
    ///
    /// ELIP151 hashes the script pubkeys the descriptor derives, and
    /// `sortedmulti` orders the keys inside those scripts, so the result is
    /// the same whichever order the xpubs arrive in.
    fn elip151_master_key_hex(threshold: usize, xpubs: &[String]) -> Result<String, TemplarError> {
        let script: Descriptor<DescriptorPublicKey> = Self::script_descriptor(threshold, xpubs)
            .parse()
            .map_err(|e| LiquidError::InvalidDescriptor(format!("multisig script: {e}")))?;
        match BlindingKey::from_elip151(&script) {
            // elements-miniscript hands the digest back as a single view key;
            // its secret bytes are the digest (reduced mod n, as the spec says).
            Ok(BlindingKey::View(DescriptorSecretKey::Single(single))) => {
                Ok(hex::encode(single.key.inner.secret_bytes()))
            }
            Ok(_) => Err(LiquidError::InvalidDescriptor(
                "ELIP151 derived something other than a single key".into(),
            )
            .into()),
            Err(e) => Err(LiquidError::InvalidDescriptor(format!("ELIP151: {e}")).into()),
        }
    }

    /// Derives the keyorigin+xpub string for a BIP39 mnemonic using BIP87.
    ///
    /// Returns `[fingerprint/87h/1h/0h]tpub...` — the format consumed by the
    /// Liquid multisig setup wizard. Used by singlesig software wallets to
    /// export their BIP87 xpub for a future Liquid multisig.
    pub fn derive_xpub_from_mnemonic(mnemonic: &str) -> Result<String, TemplarError> {
        let signer = SwSigner::new(mnemonic, false)
            .map_err(|e| LiquidError::InvalidDescriptor(format!("SwSigner: {e}")))?;
        Self::derive_xpub(&signer)
    }

    /// Signs a PSET with every local seed that belongs to the wallet.
    ///
    /// One pass per seed: LWK's `SwSigner` walks the PSET and signs every input
    /// whose `bip32_derivation` names that master fingerprint, so a wallet
    /// holding two of the N cosigner keys reaches a 2-of-3 threshold on its
    /// own. Returns the total number of signatures added.
    ///
    /// Zero added is *not* an error here — the caller decides, because a
    /// coordinator with no local key legitimately adds none.
    pub fn sign_pset_with_mnemonics(
        pset: &mut PartiallySignedTransaction,
        mnemonics: &[String],
    ) -> Result<u32, TemplarError> {
        let mut added = 0;
        for mnemonic in mnemonics {
            let signer = SwSigner::new(mnemonic, false)
                .map_err(|e| LiquidError::SigningFailed(format!("SwSigner: {e}")))?;
            added += signer
                .sign(pset)
                .map_err(|e| LiquidError::SigningFailed(e.to_string()))?;
        }
        Ok(added)
    }

    /// Name under which a Jade stores this wallet's multisig registration.
    ///
    /// Jade allows 16 characters and keys its registrations by name, so the
    /// name has to be stable across sessions *and* distinct per descriptor: a
    /// second wallet registered under a name already on the device would
    /// replace the first, and the device would then refuse to sign for it.
    /// Hence wallet name (readable) + a digest of the descriptor (unique).
    pub fn jade_multisig_name(wallet_name: &str, descriptor: &str) -> String {
        let mut base: String = wallet_name
            .chars()
            .filter(char::is_ascii_alphanumeric)
            .take(9)
            .collect();
        if base.is_empty() {
            base.push_str("templar");
        }
        let digest = sha256::Hash::hash(descriptor.as_bytes()).to_string();
        let name = format!("{base}{}", &digest[..6]);
        debug_assert!(name.len() <= JADE_MULTISIG_NAME_MAX);
        name
    }

    /// Creates a Liquid multisig descriptor from multiple mnemonics (for testing/development).
    ///
    /// In production, each participant provides their xpub via `derive_xpub`.
    pub fn from_mnemonics(
        threshold: usize,
        mnemonics: &[&str],
        blinding: &BlindingKeySource,
    ) -> Result<String, TemplarError> {
        let mut xpubs = Vec::new();
        for mnemonic in mnemonics {
            let signer = SwSigner::new(mnemonic, false)
                .map_err(|e| LiquidError::InvalidDescriptor(format!("SwSigner: {e}")))?;
            xpubs.push(Self::derive_xpub(&signer)?);
        }
        Self::build_descriptor(threshold, &xpubs, blinding)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_MNEMONIC_A: &str =
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
    const TEST_MNEMONIC_B: &str = "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong";

    #[test]
    fn derive_xpub_bip87() {
        let signer = SwSigner::new(TEST_MNEMONIC_A, false).unwrap();
        let xpub = LiquidMultisigSetup::derive_xpub(&signer).unwrap();
        assert!(xpub.contains("/87h/1h/0h]"));
        assert!(xpub.starts_with('['));
        assert!(xpub.contains("tpub"));
    }

    #[test]
    fn build_2of2_random_blinding() {
        let signer_a = SwSigner::new(TEST_MNEMONIC_A, false).unwrap();
        let signer_b = SwSigner::new(TEST_MNEMONIC_B, false).unwrap();
        let xpub_a = LiquidMultisigSetup::derive_xpub(&signer_a).unwrap();
        let xpub_b = LiquidMultisigSetup::derive_xpub(&signer_b).unwrap();

        let desc = LiquidMultisigSetup::build_descriptor(
            2,
            &[xpub_a, xpub_b],
            &BlindingKeySource::RandomSlip77,
        )
        .unwrap();

        assert!(desc.starts_with("ct(slip77("));
        assert!(desc.contains("elwsh(sortedmulti(2,"));
        assert!(desc.contains("/<0;1>/*"));
    }

    /// The property the whole co-signing flow rests on: two parties who hold
    /// the same keys — in whatever order — build byte-for-byte the same
    /// wallet, blinding key included. A random key here meant every co-signer
    /// held a different Liquid wallet and could neither read nor finalize the
    /// coordinator's PSET.
    #[test]
    fn elip151_descriptor_is_the_same_for_every_party() {
        let a = LiquidMultisigSetup::derive_xpub_from_mnemonic(TEST_MNEMONIC_A).unwrap();
        let b = LiquidMultisigSetup::derive_xpub_from_mnemonic(TEST_MNEMONIC_B).unwrap();
        let ab = LiquidMultisigSetup::build_descriptor(
            2,
            &[a.clone(), b.clone()],
            &BlindingKeySource::Elip151,
        )
        .unwrap();
        let ba = LiquidMultisigSetup::build_descriptor(
            2,
            &[b.clone(), a.clone()],
            &BlindingKeySource::Elip151,
        )
        .unwrap();
        assert_eq!(ab, ba, "key order must not change the wallet");
        // Raw SLIP77 bytes in the descriptor — the form a Jade registers.
        assert!(ab.starts_with("ct(slip77("), "{ab}");
        assert!(ab.contains("elwsh(sortedmulti(2,"), "{ab}");
        let _parsed: WolletDescriptor = ab.parse().expect("LWK opens it");
        // Stable: the same keys tomorrow give the same wallet.
        let again =
            LiquidMultisigSetup::build_descriptor(2, &[b, a], &BlindingKeySource::Elip151).unwrap();
        assert_eq!(ab, again);
        // A different key set is a different wallet.
        let other =
            LiquidMultisigSetup::from_mnemonics(1, &[TEST_MNEMONIC_A], &BlindingKeySource::Elip151)
                .unwrap();
        assert_ne!(ab, other);
    }

    #[test]
    fn build_from_mnemonics() {
        let desc = LiquidMultisigSetup::from_mnemonics(
            2,
            &[TEST_MNEMONIC_A, TEST_MNEMONIC_B],
            &BlindingKeySource::RandomSlip77,
        )
        .unwrap();
        assert!(desc.contains("elwsh(sortedmulti(2,"));
    }

    #[test]
    fn invalid_threshold_zero() {
        let signer = SwSigner::new(TEST_MNEMONIC_A, false).unwrap();
        let xpub = LiquidMultisigSetup::derive_xpub(&signer).unwrap();
        let result =
            LiquidMultisigSetup::build_descriptor(0, &[xpub], &BlindingKeySource::RandomSlip77);
        assert!(result.is_err());
    }

    #[test]
    fn invalid_threshold_exceeds() {
        let signer = SwSigner::new(TEST_MNEMONIC_A, false).unwrap();
        let xpub = LiquidMultisigSetup::derive_xpub(&signer).unwrap();
        let result =
            LiquidMultisigSetup::build_descriptor(3, &[xpub], &BlindingKeySource::RandomSlip77);
        assert!(result.is_err());
    }

    #[test]
    fn jade_name_fits_the_device_limit_and_is_descriptor_unique() {
        let a = LiquidMultisigSetup::jade_multisig_name(
            "Corporate Treasury",
            "ct(slip77(aa),elwsh(multi(2,x,y)))",
        );
        let b = LiquidMultisigSetup::jade_multisig_name(
            "Corporate Treasury",
            "ct(slip77(bb),elwsh(multi(2,x,y)))",
        );
        assert!(a.len() <= JADE_MULTISIG_NAME_MAX, "{a}");
        assert!(a.starts_with("Corporate"));
        assert_ne!(a, b, "two descriptors must not share one registration slot");
        // Stable across calls — the device is asked for the same name next time.
        assert_eq!(
            a,
            LiquidMultisigSetup::jade_multisig_name(
                "Corporate Treasury",
                "ct(slip77(aa),elwsh(multi(2,x,y)))"
            )
        );
    }

    #[test]
    fn jade_name_survives_a_name_with_no_usable_characters() {
        let n =
            LiquidMultisigSetup::jade_multisig_name("——  ✨", "ct(slip77(aa),elwsh(multi(2,x,y)))");
        assert!(n.starts_with("templar"));
        assert!(n.len() <= JADE_MULTISIG_NAME_MAX);
    }
}
